# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZwM13IHU__Zq6mlgEkReR-vHT7GaU1Y
"""

!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Contador").getOrCreate()
readme = "README.md"
rdd = spark.sparkContext.textFile(readme)
contador = (
    rdd.flatMap(lambda line: line.split()).map(lambda word: 1).reduce(lambda a, b: a + b)
)
print(f"total de palavras = {contador}")